// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3sHZdCAaoBY_KESJP60YmLW7CyXuVvEM',
    appId: '1:89634379752:web:8d6e93aa3937dd47fe365d',
    messagingSenderId: '89634379752',
    projectId: 'tapadacommunity',
    authDomain: 'tapadacommunity.firebaseapp.com',
    storageBucket: 'tapadacommunity.appspot.com',
    measurementId: 'G-DSV5HPRHCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1l8HcS--eaH3ppcESPxjdW-nX71Vq1lI',
    appId: '1:89634379752:android:71eee55095467deefe365d',
    messagingSenderId: '89634379752',
    projectId: 'tapadacommunity',
    storageBucket: 'tapadacommunity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0s5AC7MH2fW0oXprDOJ4y5WgYgEFqkw',
    appId: '1:89634379752:ios:fd9dda0356c904d5fe365d',
    messagingSenderId: '89634379752',
    projectId: 'tapadacommunity',
    storageBucket: 'tapadacommunity.appspot.com',
    iosClientId:
        '89634379752-5pd5hs7lb299v1p39gunok0oucein3jp.apps.googleusercontent.com',
    iosBundleId: 'org.acitmmm.tapadacommunity',
  );
}
